# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 7
      semver-minor-days: 1
      semver-patch-days: 1
    groups:
      aws-cdk:
        patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
          - "constructs"
          - "@aws-cdk/*"
        update-types:
          - "minor"
          - "patch"
      aws-lambda-powertools:
        patterns:
          - "@aws-lambda-powertools/*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "neostandard"
        update-types:
          - "minor"
          - "patch"
      types:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@tsconfig/*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 7
      semver-minor-days: 1
      semver-patch-days: 1
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
